# Generated by Django 5.2.7 on 2025-10-05 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='materi/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='SubMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('isi', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materi/files/')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='materi/images/')),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submateri', to='materi.materiutama')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
    ]
