# Generated by Django 5.2.7 on 2025-12-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiutama',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
