# Generated by Django 5.2.7 on 2026-02-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0002_alter_materiutama_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiutama',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MateriFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materi/files/')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submateri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='materi.submateri')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
    ]
