# Generated by Django 5.2.7 on 2026-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('siswa', 'Siswa'), ('guru', 'Guru')], default='siswa', max_length=10),
        ),
    ]
